config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :posts
  end
  resources :posts do
    resources :comments
  end
  root "posts#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.admin?
        can :manage, :all
    elsif
        can :manage, Comment, user: user
        can :read, Post
    end
  end 

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  # 每页显示文章数目
  paginates_per 5
  # 文章标题
  field :review,              type: String
  validates :review, presence: true

  # 关联关系
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  # 每页显示文章数目
  paginates_per 5
  # 文章标题
  field :title,              type: String
  validates :title, presence: true
  # 文章内容
  field :content,               type: String
  validates :content, presence: true

  # 关联关系
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  # 用户名
  field :user_name, type: String
  # 角色
  field :role, type: String

  def admin?
   role == 'admin'
  end

  # 关联关系
  has_many :posts
  has_many :comments
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  before_action :set_admin_blog, only: [:show, :edit, :update, :destroy]

  # GET /admin/blogs
  # GET /admin/blogs.json
  def index
    @admin_blogs = Admin::Blog.all
  end

  # GET /admin/blogs/1
  # GET /admin/blogs/1.json
  def show
  end

  # GET /admin/blogs/new
  def new
    @admin_blog = Admin::Blog.new
  end

  # GET /admin/blogs/1/edit
  def edit
  end

  # POST /admin/blogs
  # POST /admin/blogs.json
  def create
    @admin_blog = Admin::Blog.new(admin_blog_params)

    respond_to do |format|
      if @admin_blog.save
        format.html { redirect_to @admin_blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @admin_blog }
      else
        format.html { render :new }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/blogs/1
  # PATCH/PUT /admin/blogs/1.json
  def update
    respond_to do |format|
      if @admin_blog.update(admin_blog_params)
        format.html { redirect_to @admin_blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_blog }
      else
        format.html { render :edit }
        format.json { render json: @admin_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/blogs/1
  # DELETE /admin/blogs/1.json
  def destroy
    @admin_blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_blog
      @admin_blog = Admin::Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_blog_params
      params.require(:admin_blog).permit(:title, :description)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  layout "admin"

  def index
    @posts = Post.all
    @posts = @posts.page params[:page]
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end
  def comment_params
    params.require(:comment).permit(:review)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  load_and_authorize_resource
  before_action :set_post, only: [:show]
  layout "admin"
  def index
    @posts = Post.all
    @posts = @posts.page params[:page]
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin, @post] do |f| %>
    <%= f.input :title,                label: "文章标题" %>
    <%= f.input :content,              label: "文章内容" %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
    <div class="col-sm-10 col-sm-offset-2">
        <%= f.button :submit, "提 交", class: "btn btn-primary" %>
        <%= link_to "返 回", admin_posts_path, class: "btn btn-default" %>
    </div>
<% end %>

app/views/admin/posts/_post.html.erb
<tr>
  <td><%= link_to(post.title, admin_post_path(post)) %></td>
  <td><%= post.user.try(:email) %></td>
  <td><%= link_to("查看博客文章内容", admin_post_path(post))%></td>
  <td>
    <%= link_to("编辑", edit_admin_post_path(post), class: "btn btn-xs btn-primary")%>|
    <%= link_to("删除", admin_post_path(post), method: :delete, class: "btn btn-xs btn-primary")%>
  </td>
</tr>

app/views/admin/posts/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading font-bold">
        编辑博客文章信息
    </div>
    <div class="panel-body">
      <%= render "form", post: @post %>
    </div>
</div>

app/views/admin/posts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    博客文章管理
    <div class="pull-right">
      <%= link_to "新建博客文章", new_admin_post_path, class: "btn btn-primary btn-xs" %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
    <thead>
      <tr>
        <th>博客文章标题</th>
        <th>博客文章创建者</th>
        <th></th>
        <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <%= render(@posts) %>
      </tbody>
    </table>
  </div>

  <footer class="panel-footer">
    <%= render partial: "shared/admin/paginate", locals: { object: @posts } %>
  </footer>

</div>

app/views/admin/posts/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading font-bold">
        新建博客文章信息
    </div>
    <div class="panel-body">
      <%= render "form", post: @post %>
    </div>
</div>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= raw @post.content %>
</p>


<%= link_to '编辑文章', edit_admin_post_path(@post) ,class: "btn btn-default" %> |
<%= link_to '返回首页', admin_posts_path ,class: "btn btn-default"%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>【<%= @current_site&.name || "文章收集" %>】后台管理</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="/css/animate.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/simple-line-icons.css" type="text/css" />
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/app.min.css" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :style %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="app app-header-fixed ">
      <!-- header -->
      <%= render "shared/admin/header" %>
      <!-- / header -->
      <!-- aside -->
      <%= render "shared/admin/sidemenu" %>
      <!-- / aside -->
      <!-- content -->
      <div id="content" class="app-content">
        <div class="app-content-body ">
          <div class="bg-light lter b-b wrapper-md" id="title-content">
            <h1 class="m-n font-thin h3"><%= @title %></h1>
          </div>
          <div class="wrapper-md">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>">
                <%= value %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
      <!-- /content -->
      <!-- footer -->
      <%= render "shared/admin/footer" %>
      <!-- / footer -->
    </div>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/ui-nav.js"></script>
    <script src="/js/ui-toggle.js"></script>
    <script src="/js/vue.min.js"></script>
    <script src="/js/vue-resource.min.js"></script>
    <%= yield :script %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<tr>
  <td><%= link_to(post.title, admin_post_path(post)) %></td>
  <td><%= post.user.try(:email) %></td>
  <td><%= link_to("查看博客文章内容", post_path(post))%></td>
</tr>

app/views/posts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    博客文章首页
  </div>

  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
    <thead>
      <tr>
        <th>博客文章标题</th>
        <th>博客文章创建者</th>
        <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render(@posts) %>
      </tbody>
    </table>
  </div>

<footer class="panel-footer">
  <%= render partial: "shared/admin/paginate", locals: { object: @posts } %>
</footer>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= raw @post.content %>
</p>


<%= link_to '返回首页', admin_posts_path ,class: "btn btn-default"%>


<br>
<br>
<br>
<br>


<div class="panel panel-default">
    <div class="pull-right">
      <%= link_to "写评论", new_post_comment_path(@post), class: "btn btn-primary btn-xs" %>
    </div>
    <div class="panel-body">
      <%= simple_form_for [@post, @comment] do |f| %>
          <%= f.input :review,              label: "评论" %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
          <div class="col-sm-10 col-sm-offset-2">
              <%= f.button :submit, "提 交", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
<div class="panel panel-default">
  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
    <thead>
      <tr>
        <th>评论内容</th>
        <th>评论作者</th>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.review %></td>
            <td><%= comment.user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/admin/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-error">
     The form contains <%= pluralize(object.errors.count, "error") %>.
   </div>
  <ul>
   <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/admin/_footer.html.erb
<footer id="footer" class="app-footer" role="footer">
  <div class="wrapper b-t bg-light">
    <span class="pull-right"> <a href ui-scroll="app" class="m-l-sm text-muted"><i class="fa fa-long-arrow-up"></i></a></span>
    &copy; 2017 Copyright.
  </div>
</footer>

app/views/shared/admin/_header.html.erb
<header id="header" class="app-header navbar" role="menu">
  <!-- navbar header -->
  <div class="navbar-header bg-dark">
    <button class="pull-right visible-xs dk" ui-toggle-class="show" target=".navbar-collapse">
      <i class="glyphicon glyphicon-cog"></i>
    </button>
    <button class="pull-right visible-xs" ui-toggle-class="off-screen" target=".app-aside" ui-scroll="app">
      <i class="glyphicon glyphicon-align-justify"></i>
    </button>
    <!-- brand -->
    <% if can? :read, User %>
      <div class="block m-l-sm m-t-sm">
        <a href="/" >
          <h2>后台管理</h2>
        </a>
      </div>
    <% end %>
    <!-- / brand -->
  </div>
  <!-- / navbar header -->

  <!-- navbar collapse -->
  <div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">

    <!-- link and dropdown -->
    <ul class="nav navbar-nav hidden-sm">
      <li class="dropdown pos-stc">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
          <span>快捷菜单</span>
          <span class="caret"></span>
        </a>
        <div class="dropdown-menu wrapper w-full bg-white">
          <div class="row">
            <div class="col-sm-6">
              <div class="row">
                <div class="col-xs-6">
                  <ul class="list-unstyled l-h-2x">
                    <li>
                      <a href="/admin/coupons/expire"><i class="fa fa-fw fa-angle-right text-muted m-r-xs"></i>卡券批量操作</a>
                    </li>
                    <li>
                      <a href="/admin/merchants/new"><i class="fa fa-fw fa-angle-right text-muted m-r-xs"></i>新建商户</a>
                    </li>
                    <li>
                    </li>
                  </ul>
                </div>
                <div class="col-xs-6">
                  <ul class="list-unstyled l-h-2x">
                    <li>
                    </li>
                    <li>
                    </li>
                    <li>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
    <!-- / link and dropdown -->

    <!-- search form -->
    <form class="navbar-form navbar-form-sm navbar-left shift" ui-shift="prependTo" data-target=".navbar-collapse" role="search" ng-controller="TypeaheadDemoCtrl">
      <div class="form-group">
        <div class="input-group">
          <input type="text" ng-model="selected" typeahead="state for state in states | filter:$viewValue | limitTo:8" class="form-control input-sm bg-light no-border rounded padder" placeholder="搜索">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-sm bg-light rounded"><i class="fa fa-search"></i></button>
          </span>
        </div>
      </div>
    </form>
    <!-- / search form -->

    <!-- nabar right -->
    <ul class="nav navbar-nav navbar-right" id="merchant_not_yz">
      <li class="dropdown" style="padding-bottom: 15px;padding-top: 15px">
        <small><%= @current_site&.domain || "" %></small>
      </li>
      <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
          <i class="icon-bell fa-fw"></i>
          <span class="visible-xs-inline">通知消息</span>
        </a>
        <!-- dropdown -->
        <div class="dropdown-menu w-xl animated fadeInUp">
          <div class="panel bg-white notice_div">
            <div class="panel-heading b-light bg-light">
              <strong>你有<span class="notice_count">{{not_yz_users.length}}</span>条未验证信息</strong>
            </div>
            <div class="list-group" v-for="user in not_yz_users">
              <a href="/admin/merchants/{{user.merchant_id}}/edit" class="list-group-item">
                <span class="pull-left m-r thumb-sm">
                  <img :src="user.headimg" alt="..." class="img-circle">
                </span>
                <span class="clear block m-b-none">
                  {{user.merchant_name}}<br>
                  <small class="text-muted">{{user.username}}申请验证员审核</small>
                </span>
              </a>
            </div>
          </div>
        </div>
        <!-- / dropdown -->
      </li>
      <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle clear" data-toggle="dropdown">
          <span class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm">
            <i class="on md b-white bottom"></i>
          </span>
          <% if !current_user %>
             <li><%= link_to("登录", new_user_session_path) %></li>|
             <li><%= link_to("注册", new_user_registration_path) %></li>
          <% else %>
            <hi><%= current_user.email %></hi>
            <li><%= link_to("登出", destroy_user_session_path, method: :delete)%></li>
          <% end %>
    </ul>
    <!-- / navbar right -->
  </div>
  <!-- / navbar collapse -->
</header>

<%= content_for :script do %>
  <script>
var App = new Vue({
  el: '#merchant_not_yz',
  data: {
    not_yz_users: [], // my list for the v-for
  },
  created: function () {
  },
});
  </script>
<% end %>

app/views/shared/admin/_paginate.html.erb
<div class="row">
  <div class="col-sm-4 text-left">
    <small class="text-muted inline m-t-sm m-b-sm">共有<%= object.total_count %>个项目</small>
  </div>
  <div class="col-sm-8 text-right text-center-xs">
    <%= paginate object, views_prefix: 'admin', theme: 'angulr' %>
  </div>
</div>

app/views/shared/admin/_sidemenu.html.erb
<aside id="aside" class="app-aside app-aside-fixed hidden-xs bg-dark">
  <div class="aside-wrap">
    <div class="navi-wrap">
      <!-- nav -->
      <nav ui-nav class="navi clearfix">
        <ul class="nav">
          <% if can? :read, User %>
            <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
              <span>导航</span>
            </li>
          <% end %>
          <% if can? :read, User %>
            <li class="<%= "active" if controller_name == "home" %>">
              <a href="/admin/home" class="auto">
                <i class="glyphicon glyphicon-stats icon text-primary"></i>
                <span class="font-bold">控制面板</span>
              </a>
            </li>
          <% end %>

          <% if can? :read, User %>
            <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
              <span>平台管理</span>
            </li>
          <% end %>

            <li class="<%= "active" if controller_name == "posts" %>">
              <a href="/" class="auto">
                <i class="fa fa-file-text"></i>
                <span>博客</span>
              </a>
            </li>

          <% if can? :read, User %>
            <li class="<%= "active" if controller_name == "admin::posts" %>">
              <a href="/admin/posts" class="auto">
                <i class="fa fa-file-text"></i>
                <span>后台博客</span>
              </a>
            </li>
          <% end %>

          <li class="line dk hidden-folded"></li>
        </ul>
      </nav>
      <!-- nav -->
    </div>
  </div>
</aside>